# Generated by Django 4.2.4 on 2023-08-02 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('funcionarios', '0002_funcionario_empresa_funcionario_departamentos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='Empresa',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='empresa.empresa'),
        ),
    ]
