# Generated by Django 4.2.4 on 2023-08-04 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_departamento_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='Empresa',
            new_name='empresa',
        ),
    ]
