# Generated by Django 4.2.4 on 2023-08-04 21:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_documento_pertence'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(default=django.utils.timezone.now, upload_to='documentos'),
            preserve_default=False,
        ),
    ]
